version: 2

sources:
  - name: s1
    database: dbt_customers
    schema: dbt_schema  
    tables:
      - name: tbl_customer
      - name: tbl_nation
      - name: tbl_tickets
      - name: tbl_bus_tickets
      